# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('img', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('company', models.CharField(max_length=120)),
                ('info', models.CharField(max_length=255)),
                ('in_cart', models.BooleanField(default=False)),
                ('count', models.IntegerField()),
                ('total', models.IntegerField()),
                ('tax', models.IntegerField()),
            ],
        ),
    ]
