# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonestore',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
